---
kind: ApplicationShell
applicationShellName: John EEE John Petes # Name for Application Shell
shellTypeId: 9a811244-5840-4e37-ad5c-369f731784e6 # Shell Type
namespace: default # Create a namespace to segregate for each client or tenant.